[package]
name = "aptos_random_hack"
version = "1.0.0"
upgrade_policy = "compatible"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git' 
rev = 'main'
subdir = 'aptos-move/framework/aptos-token-objects'

[addresses]
self = "0x5368fda23c48aecfadc109397e200c4a8b7621f833c2fe293d6fc6ae78cd7e7b"
std = "0x1"
aptos_token_objects ="0x4"


